[pytest]
filterwarnings =
    ignore::DeprecationWarning:pydantic.*
    ignore::DeprecationWarning:PyPDF2.*
    ignore::DeprecationWarning:importlib.*
    ignore:builtin type Swig:DeprecationWarning
    ignore:builtin type swigvarlink:DeprecationWarning
